## Creating ndarray
- numpy.array is just a convenience function to create an ndarray
- numpy.ndarray is a class

In [1]:
import numpy

In [6]:
import numpy as np

oneDim = np.array([1.0, 2, 3, 4, 5])
print(oneDim)
print("#Dimensions = ", oneDim.ndim)
print("Dimension = ",oneDim.shape)
print("Size = ", oneDim.size)
print("Array type = ", oneDim.dtype)

twoDim = np.array([[1,2],[3,4],[5,6]])
print(twoDim)
print("#Dimensions = ", twoDim.ndim)
print("Dimension = ",twoDim.shape)
print("Size = ", twoDim.size)
print("Array type = ", twoDim.dtype)

[1. 2. 3. 4. 5.]
#Dimensions =  1
Dimension =  (5,)
Size =  5
Array type =  float64
[[1 2]
 [3 4]
 [5 6]]
#Dimensions =  2
Dimension =  (3, 2)
Size =  6
Array type =  int32


numpy 배열은 한가지 타입으로 구성

In [7]:
arrFormTuple = np.array([(1, 'a', 3.0), (2, 'b', 3.5)])
print(arrFormTuple)
print(arrFormTuple.ndim)
print(arrFormTuple.shape)
print(arrFormTuple.size)
print(arrFormTuple.dtype)

[['1' 'a' '3.0']
 ['2' 'b' '3.5']]
2
(2, 3)
6
<U11


In [10]:
print(np.array([1]).shape)
print(np.array([1,2]).shape)
print(np.array([[1],[2]]).shape)
print(np.array([[[1,2,3],[4,5,6]]]).shape)
print(np.array([[[[[]]]]]).shape)

(1,)
(2,)
(2, 1)
(1, 2, 3)
(1, 1, 1, 1, 0)


In [16]:
(1,2) == (1,2,)

True

In [25]:
print(np.random.rand(5))
print(np.random.randn(5))
print(np.arange(-10, 10, 2)) # range랑 비슷한데 list반환이 아니라 ndarray반환
print([i for i in range(10)])
print(np.arange(12).reshape(3,4))
print(np.linspace(0,1,10)) #0부터 1사이를 10등분한다.
print(np.linspace(0, 4,10))
print(np.logspace(-3,3,7))

[0.44741658 0.71647706 0.13143828 0.62394427 0.67422952]
[-1.0176896   1.15587511 -0.34051323 -2.1024969   0.90394426]
[-10  -8  -6  -4  -2   0   2   4   6   8]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
[0.         0.44444444 0.88888889 1.33333333 1.77777778 2.22222222
 2.66666667 3.11111111 3.55555556 4.        ]
[1.e-03 1.e-02 1.e-01 1.e+00 1.e+01 1.e+02 1.e+03]


In [28]:
print(np.zeros((2,3)))
print(np.zeros((1)))
print(np.ones((3,2)))
print(np.eye(3))

[[0. 0. 0.]
 [0. 0. 0.]]
[0.]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [29]:
x=np.array([1,2,3,4,5])

print(x*1)
print(x-1)
print(x//2) # 몫 : 정수
print(x/2)  # 몫 : 실수
print(x%2)
print(1/x)

[1 2 3 4 5]
[0 1 2 3 4]
[0 1 1 2 2]
[0.5 1.  1.5 2.  2.5]
[1 0 1 0 1]
[1.         0.5        0.33333333 0.25       0.2       ]


In [30]:
x = np.array([2,4,6,8,10])
y = np.array([1,2,3,4,5])

print(x+y)
print(x-y)
print(x*y)
print(x**y)
print(x/y)
print(x//y)

[ 3  6  9 12 15]
[1 2 3 4 5]
[ 2  8 18 32 50]
[     2     16    216   4096 100000]
[2. 2. 2. 2. 2.]
[2 2 2 2 2]


In [31]:
x=np.arange(-5,5)
print(x)

y=x[3:5] # indexing
print(y)
y[:] = 1000 # x의 값도 변한다
print(y)
print(x)

z=x[3:5].copy() # copying
print(z)
z[:]=500
print(z)
print(x) # x값 불변

[-5 -4 -3 -2 -1  0  1  2  3  4]
[-2 -1]
[1000 1000]
[  -5   -4   -3 1000 1000    0    1    2    3    4]
[1000 1000]
[500 500]
[  -5   -4   -3 1000 1000    0    1    2    3    4]


In [32]:
x= list(range(-5, 5))
print(x)

y = x[3:5] # index 3,4
print(y)
y[1]=1000
print(y)
print(x)

[-5, -4, -3, -2, -1, 0, 1, 2, 3, 4]
[-2, -1]
[-2, 1000]
[-5, -4, -3, -2, -1, 0, 1, 2, 3, 4]


In [33]:
my2dlist = [[1,2,3,4],[5,6,7,8],[9,10,11,12]]
print(my2dlist)
print(my2dlist[2]) #9.10.11.12
print(my2dlist[:][2]) # 각원소의 2번째 원소에 접근 불가
print("=====================")

my2darr = np.array(my2dlist) #list를 numpy array로
print(my2darr)
print(my2darr[2][:])
print(my2darr[2,:])
print(my2darr[:][2])
print(my2darr[:,2])
print(my2darr[:2,2:]) 
print(my2darr[::2,2:])

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
[9, 10, 11, 12]
[9, 10, 11, 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[ 9 10 11 12]
[ 9 10 11 12]
[ 9 10 11 12]
[ 3  7 11]
[[3 4]
 [7 8]]
[[ 3  4]
 [11 12]]


# It's indexing, not copying!

In [34]:
my2darr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(my2darr)
print()
sliced = my2darr[::2,2:] # [3,4],[11,12]
print(sliced)
print(type(sliced))

print()
sliced[:,:] = 1000
print(my2darr) # change

print()
sliced[0,0]=2000
print(my2darr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[[ 3  4]
 [11 12]]
<class 'numpy.ndarray'>

[[   1    2 1000 1000]
 [   5    6    7    8]
 [   9   10 1000 1000]]

[[   1    2 2000 1000]
 [   5    6    7    8]
 [   9   10 1000 1000]]


### ndarray also supports boolean indexing(also called masking)

In [35]:
x = np.array([1,2,3])
print(x[1:])
print(x[1:][0])

print()
print(x[[True, False, True]]) # boolean indexing

print()
print(x[[2,1]])  # integer array indexing
print(x[[2,1,1,1,0]])  # integer array indexing

print()
x[[2,1,1,1,0]]=0
print(x)

[2 3]
2

[1 3]

[3 2]
[3 2 2 2 1]

[0 0 0]


In [39]:
y=np.arange(35).reshape(5,7)
b=y>20
print(b)

print()
t=y[b]
print(t)

print()
t[:3]=1000
print(t)
print(y)

[[False False False False False False False]
 [False False False False False False False]
 [False False False False False False False]
 [ True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True]]

[21 22 23 24 25 26 27 28 29 30 31 32 33 34]

[1000 1000 1000   24   25   26   27   28   29   30   31   32   33   34]
[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]]


In [43]:
M = np.arange(35).reshape(5,7)
M
print(M)

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]]


In [44]:
M[M%2==0]=0
print(M)

[[ 0  1  0  3  0  5  0]
 [ 7  0  9  0 11  0 13]
 [ 0 15  0 17  0 19  0]
 [21  0 23  0 25  0 27]
 [ 0 29  0 31  0 33  0]]


In [46]:
M[M%2==1] = -M[M%2==1]
M

array([[  0,  -1,   0,  -3,   0,  -5,   0],
       [ -7,   0,  -9,   0, -11,   0, -13],
       [  0, -15,   0, -17,   0, -19,   0],
       [-21,   0, -23,   0, -25,   0, -27],
       [  0, -29,   0, -31,   0, -33,   0]])

In [47]:
np.where(M%2==0, M, -M) # M중에서 조건 만족하는 애들은 -M

array([[ 0,  1,  0,  3,  0,  5,  0],
       [ 7,  0,  9,  0, 11,  0, 13],
       [ 0, 15,  0, 17,  0, 19,  0],
       [21,  0, 23,  0, 25,  0, 27],
       [ 0, 29,  0, 31,  0, 33,  0]])

#### integer array indexing

In [55]:
my2darr = np.arange(1,13,1).reshape(4,3)
print(my2darr)

indices = [2,1,0,3]
print(my2darr[indices,:])

rowIndex= [0,0,1,2,3]
columnIndex = [0,2,0,1,2]
print(my2darr[rowIndex,columnIndex])

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 7  8  9]
 [ 4  5  6]
 [ 1  2  3]
 [10 11 12]]
[ 1  3  4  8 12]


### numpy arithmetic and statistical functions

In [57]:
y = np.array([-1.4, 0.4, -3.2, 2.5, 3.4])
print(y)
print()

print(np.abs(y))
print(np.sqrt(np.abs(y)))
print(np.sign(y))
print(np.exp(y))  #exponentiation : e^y
print(np.sort(y))
print(y)

[-1.4  0.4 -3.2  2.5  3.4]

[1.4 0.4 3.2 2.5 3.4]
[1.18321596 0.63245553 1.78885438 1.58113883 1.84390889]
[-1.  1. -1.  1.  1.]
[ 0.24659696  1.4918247   0.0407622  12.18249396 29.96410005]
[-3.2 -1.4  0.4  2.5  3.4]
[-1.4  0.4 -3.2  2.5  3.4]


In [58]:
x=np.arange(-2,3)
y=np.random.randn(5)
print(x)
print(y)

# element-wise
print(np.add(x,y))
print(np.subtract(x,y))
print(np.multiply(x,y))
print(np.divide(x,y))
print(np.maximum(x,y))

[-2 -1  0  1  2]
[-0.06133807  1.37866752 -0.0683584  -0.11663734 -1.31514092]
[-2.06133807  0.37866752 -0.0683584   0.88336266  0.68485908]
[-1.93866193 -2.37866752  0.0683584   1.11663734  3.31514092]
[ 0.12267614 -1.37866752 -0.         -0.11663734 -2.63028184]
[32.60617833 -0.72533804 -0.         -8.5735837  -1.52074958]
[-0.06133807  1.37866752  0.          1.          2.        ]


In [59]:
y = np.array([-3.2,-1.4,0.4,2.5,3.4])
print(y)

print("Min = ", np.min(y))
print("Max = ", np.max(y))
print("average = ", np.mean(y))
print("std deviation = ", np.std(y))
print("sum = ", np.sum(y))

[-3.2 -1.4  0.4  2.5  3.4]
Min =  -3.2
Max =  3.4
average =  0.34000000000000014
std deviation =  2.432776191925595
sum =  1.7000000000000006


In [61]:
M = np.arange(25).reshape(5,5)
print(M)
print(M[M%2==1])
print(np.argwhere(M >= 20))
print(np.where(M%2 == 1, M, 0))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[ 1  3  5  7  9 11 13 15 17 19 21 23]
[[4 0]
 [4 1]
 [4 2]
 [4 3]
 [4 4]]
[[ 0  1  0  3  0]
 [ 5  0  7  0  9]
 [ 0 11  0 13  0]
 [15  0 17  0 19]
 [ 0 21  0 23  0]]


## New axis
- used to increase the dimension of the existing array by one more dimension
- shape change, for example: nX(newaxis)Xm -> nX1Xm

In [64]:
t= np.array([1,2,3])
print(t.shape)
x = t[:,np.newaxis]  # 3*1
print(x.shape)
y=t[np.newaxis, :]  #1*3
print(y.shape)

(3,)
(3, 1)
(1, 3)


In [65]:
print(x)
print(y)
print(t)

[[1]
 [2]
 [3]]
[[1 2 3]]
[1 2 3]


### Axis가 맞지 않으면 맞춰준다 : Broadcasting

In [66]:
x+y
# shape를 맞춰준다.
# x
# [[1,1,1],[2,2,2],[3,3,3]]
# y
# [[1,2,3],[1,2,3],[1,2,3]]
print(x+y)

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [68]:
t= np.array([[1,2,3],[4,5,6]])  #(2,3)
print(t)
print()

print(t[:,:,np.newaxis].shape)  #맨마지막에 axis를 추가
print(t[:,:,np.newaxis])  #2,3,1
print()

print(t[:,np.newaxis,:].shape) #2,1,3
print(t[:,np.newaxis,:])
print()

print(t[np.newaxis,:,:].shape)  #1,2,3
print(t[np.newaxis, :,:])

[[1 2 3]
 [4 5 6]]

(2, 3, 1)
[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]]

(2, 1, 3)
[[[1 2 3]]

 [[4 5 6]]]

(1, 2, 3)
[[[1 2 3]
  [4 5 6]]]


# **Broadcasting
Broadcasting decribs how numpy treats arrays with different shapes during arithmetic operations.Subject to certain constraints, the smaller array is "breoadcast" across the larger array so that they have compatible shapes.

In [69]:
np.array([[1,2],[3,4]])+np.array([[10]])
#(2,2) + (1,1)

array([[11, 12],
       [13, 14]])

In [70]:
np.array([[1,2],[3,4]])+np.array([[10,100]])
# (2,2) + (1,2)

array([[ 11, 102],
       [ 13, 104]])

In [71]:
A=np.array([[1,2]])
B = np.array([[10],[100]])
print(A.shape, B.shape)
C = A+B
print(C)

(1, 2) (2, 1)
[[ 11  12]
 [101 102]]


In [79]:
X = np.array([[1]]*3)+np.array([[0]*10])
print(np.array([[1]]*3).shape) #axis = 0으로 3번 반복
print(np.array([[1]]*3))
print()

print(np.array([[0]*10]).shape)  #axis = 1으로 10번 반복
print(np.array([[0]*10]))
print()

print(X)

(3, 1)
[[1]
 [1]
 [1]]

(1, 10)
[[0 0 0 0 0 0 0 0 0 0]]

[[1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]]


In [81]:
a = np.array([[1],[2],[3]])
b = a.T
print(a)
print(b)
print(a+b)

[[1]
 [2]
 [3]]
[[1 2 3]]
[[2 3 4]
 [3 4 5]
 [4 5 6]]


## Meshgrid
격자점 좌표를 만드는 명령어

In [82]:
v = np.array([10,20,30])
w = np.array([5,6])
X,Y = np.meshgrid(v,w)
print(X)
print(Y)
print(X+Y)

[[10 20 30]
 [10 20 30]]
[[5 5 5]
 [6 6 6]]
[[15 25 35]
 [16 26 36]]


In [83]:
x=np.array([[0,0,0], [1,1,1]])
x.shape

(2, 3)

In [84]:
x.sum(axis=0)

array([1, 1, 1])

In [85]:
x.sum(axis=1)

array([0, 3])

In [86]:
x=np.array(range(1,24+1)).reshape(2,3,4)
x.shape

(2, 3, 4)

In [87]:
x.sum(axis=0)

array([[14, 16, 18, 20],
       [22, 24, 26, 28],
       [30, 32, 34, 36]])

In [88]:
x.sum(axis=1)

array([[15, 18, 21, 24],
       [51, 54, 57, 60]])

In [89]:
x.sum(axis=2)

array([[10, 26, 42],
       [58, 74, 90]])

In [92]:
x.sum(axis=(1,2))

array([ 78, 222])

In [93]:
x.sum(axis=(0,1,2))

300

In [96]:
import numpy as np
x=np.array(np.arange(2*3,0,-1).reshape(2,3))
print(x)
print()
print(np.sort(x,axis=0))
print()
print(np.sort(x,axis=-1))  #last axis를 기준으로 sort
print()
print(np.sort(x))  #default = -1
print()
print(np.sort(x, axis=None))

[[6 5 4]
 [3 2 1]]

[[3 2 1]
 [6 5 4]]

[[4 5 6]
 [1 2 3]]

[[4 5 6]
 [1 2 3]]

[1 2 3 4 5 6]
